#include <stdio.h>
int main()
{
    char a = '3';
    char* ptra = &a;
    printf("%d\n", ptra);      // We can use %p or %x...
    ptra++;
    printf("%d\n", ptra);     // We can use %p or %x...
    ptra--;
    printf("%d\n", ptra);     // We can use %p or %x...
    printf("%d\n", ptra+1);   // We can use %p or %x...
    printf("%d\n", ptra+2);   // We can use %p or %x...
    printf("%d\n", ptra-2);   // We can use %p or %x...
    

     
    return 0;
}
